language: ruby

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/Gemfile-5-0-stable
  - gemfiles/Gemfile-5-1-stable
  - gemfiles/Gemfile-5-2-stable
  - Gemfile

matrix:
  exclude:
    - rvm: 2.2.10
      gemfile: Gemfile
    - rvm: 2.3.8
      gemfile: Gemfile
    - rvm: 2.4.9
      gemfile: Gemfile

cache: bundler

bundler_args: --jobs 3 --retry 3

before_install:
  - "rm -f ${BUNDLE_GEMFILE}.lock"
